version: '3'
services:
  server:
    image: nginx:latest
    ports:
      - "4000:80"
    volumes:
      - ./src/public:/var/www/html
      - ./src:/var/www
      - ./vendor:/var/vendor
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:7-fpm
    volumes:
        - ./src/public:/var/www/html
        - ./src:/var/www
        - ./vendor:/var/vendor