version: '3'
services:
  server:
    image: nginx:latest
    ports:
      - "4000:80"
    volumes:
      - ./src/public:/var/www/public
      - ./src:/var/www
      - ./vendor:/var/vendor
      - ./ops/config/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    depends_on:
      - php
    restart: always
  php:
    build:
      dockerfile: ./ops/docker/phpDockerfile
      context: .
    volumes:
      - ./composer.json:/var/www/composer.json
      - ./src/public:/var/www/public
      - ./src:/var/www