version: '3'
services:
  server:
    image: nginx:latest
    ports:
      - "4000:80"
    volumes:
      - ./src/public:/var/www/html
      - ./src:/var/www
      - /var/vendor
      - ./ops/config/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build:
      dockerfile: ./ops/docker/phpDockerfile
      context: .
    volumes:
      - ./composer.json:/var/www/composer.json
      - ./src/public:/var/www/html
      - ./src:/var/www
      - /var/vendor